// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb69vtlQz_4OS9ehzg491VgdB9ANg_E-w',
    appId: '1:964126876489:web:f3c36d3b7d54f015453098',
    messagingSenderId: '964126876489',
    projectId: 'starter-db-81d3f',
    authDomain: 'starter-db-81d3f.firebaseapp.com',
    storageBucket: 'starter-db-81d3f.appspot.com',
    measurementId: 'G-GGNQ4KE9KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-s3rZB2HCvAlefUTWNN2oRJE5nG2qODY',
    appId: '1:964126876489:android:72dcdd96131266d6453098',
    messagingSenderId: '964126876489',
    projectId: 'starter-db-81d3f',
    storageBucket: 'starter-db-81d3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKB6gFENxCIiedzr3lsTGDBHZakwHxe_A',
    appId: '1:964126876489:ios:4c9231c149a12b3c453098',
    messagingSenderId: '964126876489',
    projectId: 'starter-db-81d3f',
    storageBucket: 'starter-db-81d3f.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKB6gFENxCIiedzr3lsTGDBHZakwHxe_A',
    appId: '1:964126876489:ios:4c9231c149a12b3c453098',
    messagingSenderId: '964126876489',
    projectId: 'starter-db-81d3f',
    storageBucket: 'starter-db-81d3f.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb69vtlQz_4OS9ehzg491VgdB9ANg_E-w',
    appId: '1:964126876489:web:56ae171a1ecb0546453098',
    messagingSenderId: '964126876489',
    projectId: 'starter-db-81d3f',
    authDomain: 'starter-db-81d3f.firebaseapp.com',
    storageBucket: 'starter-db-81d3f.appspot.com',
    measurementId: 'G-540PG98NTF',
  );
}
